[package]
name = "fslinkmanager"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
clap = { version = "4.5.41", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
